# Generated by Django 4.2.9 on 2024-01-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(max_length=255, verbose_name='Country (id)')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('purchase_price', models.FloatField(default=None, null=True, verbose_name='Price')),
                ('extra_fee_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price')),
                ('all_in_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Gas prijs',
                'verbose_name_plural': 'Gas prijzen',
                'ordering': ['-date'],
                'index_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(max_length=4, verbose_name='Country (id)')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('purchase_price', models.FloatField(default=None, help_text='Inkoopprijs', null=True, verbose_name='Price')),
                ('extra_fee_price', models.FloatField(blank=True, default=None, help_text='Inkoopprijs + inkoopvergoeding + BTW', null=True, verbose_name='Price')),
                ('all_in_price', models.FloatField(blank=True, default=None, help_text='Inkoopprijs + inkoopvergoeding + ODE + energiebelasting + BTW', null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Energyprice',
                'verbose_name_plural': 'Energy prices',
                'ordering': ['-date'],
                'index_together': {('date', 'time')},
            },
        ),
    ]
