# Generated by Django 4.2.7 on 2024-01-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eprijzen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyprice",
            name="all_in_price",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Inkoopprijs + inkoopvergoeding + ODE + energiebelasting + BTW",
                null=True,
                verbose_name="All-in Price",
            ),
        ),
        migrations.AlterField(
            model_name="energyprice",
            name="extra_fee_price",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Inkoopprijs + inkoopvergoeding + BTW",
                null=True,
                verbose_name="Extra Fee Price",
            ),
        ),
        migrations.AlterField(
            model_name="energyprice",
            name="purchase_price",
            field=models.FloatField(
                default=None,
                help_text="Inkoopprijs",
                null=True,
                verbose_name="Purchase Price",
            ),
        ),
        migrations.AlterField(
            model_name="gasprice",
            name="all_in_price",
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name="All-in Price"
            ),
        ),
        migrations.AlterField(
            model_name="gasprice",
            name="extra_fee_price",
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name="Extra Fee Price"
            ),
        ),
        migrations.AlterField(
            model_name="gasprice",
            name="purchase_price",
            field=models.FloatField(
                default=None, null=True, verbose_name="Purchase Price"
            ),
        ),
    ]
