# Generated by Django 4.2.9 on 2024-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprijzen', '0002_alter_energyprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(max_length=255, unique=True, verbose_name='Country id')),
                ('country_iso', models.CharField(max_length=255, unique=True, verbose_name='Country ISO')),
                ('country_name', models.CharField(max_length=255, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Landen',
            },
        ),
        migrations.CreateModel(
            name='EnergypriceEurope',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(max_length=4, verbose_name='Country (id)')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('purchase_price', models.FloatField(default=None, help_text='Inkoopprijs', null=True, verbose_name='Purchase Price')),
                ('extra_fee_price', models.FloatField(blank=True, default=None, help_text='Inkoopprijs + inkoopvergoeding + BTW', null=True, verbose_name='Extra Fee Price')),
                ('all_in_price', models.FloatField(blank=True, default=None, help_text='Inkoopprijs + inkoopvergoeding + ODE + energiebelasting + BTW', null=True, verbose_name='All-in Price')),
            ],
            options={
                'verbose_name': 'Energyprice (EU)',
                'verbose_name_plural': 'Energy prices (EU)',
                'ordering': ['country_id', '-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='GaspriceEurope',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(max_length=255, verbose_name='Country (id)')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('purchase_price', models.FloatField(default=None, null=True, verbose_name='Purchase Price')),
                ('extra_fee_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Extra Fee Price')),
                ('all_in_price', models.FloatField(blank=True, default=None, null=True, verbose_name='All-in Price')),
            ],
            options={
                'verbose_name': 'Gas prijs',
                'verbose_name_plural': 'Gas prijzen',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='energyprice',
            options={'ordering': ['country_id', '-date', '-time'], 'verbose_name': 'Energyprice (NL)', 'verbose_name_plural': 'Energy prices (NL)'},
        ),
        migrations.AlterModelOptions(
            name='gasprice',
            options={'ordering': ['-date'], 'verbose_name': 'Gas price (NL)', 'verbose_name_plural': 'Gas prices (NL)'},
        ),
        migrations.RemoveIndex(
            model_name='energyprice',
            name='eprijzen_en_country_b2fed6_idx',
        ),
        migrations.RemoveIndex(
            model_name='gasprice',
            name='eprijzen_ga_country_798de0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='gaspriceeurope',
            unique_together={('country_id', 'date', 'time')},
        ),
        migrations.AlterIndexTogether(
            name='gaspriceeurope',
            index_together={('country_id', 'date', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='energypriceeurope',
            unique_together={('country_id', 'date', 'time')},
        ),
        migrations.AlterIndexTogether(
            name='energypriceeurope',
            index_together={('country_id', 'date', 'time')},
        ),
    ]
